In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

In [3]:
print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([5,3])
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.rand([5,3])

In [6]:
print(x)

tensor([[0.5437, 0.1783, 0.7199],
        [0.5773, 0.4521, 0.2261],
        [0.7917, 0.5253, 0.0559],
        [0.2209, 0.2487, 0.3369],
        [0.5525, 0.9450, 0.7817]])


In [7]:
x.shape

torch.Size([5, 3])

In [8]:
a,b = x.shape 

In [10]:
a,b

(5, 3)

In [11]:
y = x.view([15,1])
# reshape

In [12]:
print(y)

tensor([[0.5437],
        [0.1783],
        [0.7199],
        [0.5773],
        [0.4521],
        [0.2261],
        [0.7917],
        [0.5253],
        [0.0559],
        [0.2209],
        [0.2487],
        [0.3369],
        [0.5525],
        [0.9450],
        [0.7817]])
